import { useCallback,useEffect,useState } from 'react'
import { supabaseClient } from '../lib/supabaseClient'
import type { BankAccount,Tx,PaymentRequest,Audit,Connection,Movement,History,ReconciliationItem } from '../lib/opsData'
export type AuditRow=Audit&{actor_id?:string|null;metadata?:Record<string,unknown>|null}
export type ProfileRow={id:string;full_name:string|null;email:string|null;role:'admin'|'reviewer'|'viewer';avatar_url:string|null;created_at:string;updated_at:string;last_sign_in_at:string|null;active:boolean}
export type UserGroupRow={id:string;owner_id:string;name:string;description:string|null;permissions:Record<string,boolean>;deleted_at:string|null;created_at:string}
export type UserGroupMemberRow={group_id:string;user_id:string;permission:string;created_at:string}
export type ReconciliationMatch={id:string;user_id:string;transaction_id:string;movement_id:string;matched_by:string;matched_at:string;match_type:'automatic'|'manual'}
type Resource<T>={data:T[];loading:boolean;error:string|null;refetch:()=>Promise<void>}
function useTable<T>(table:string,orderColumn:string,limit=500,realtime=false,enabled=true):Resource<T>{const[data,setData]=useState<T[]>([]),[loading,setLoading]=useState(enabled),[error,setError]=useState<string|null>(null);const refetch=useCallback(async()=>{if(!enabled){setData([]);setLoading(false);setError(null);return}if(!supabaseClient){setError('Supabase yapılandırılmamış');setLoading(false);return}setLoading(true);const r=await supabaseClient.from(table).select('*').order(orderColumn,{ascending:false}).limit(limit);setError(r.error?.message||null);setData((r.data||[]) as T[]);setLoading(false)},[table,orderColumn,limit,enabled]);useEffect(()=>{void refetch();if(!supabaseClient||!realtime||!enabled)return;const c=supabaseClient.channel(`live-${table}`).on('postgres_changes',{event:'*',schema:'public',table},()=>void refetch()).subscribe();return()=>{if(supabaseClient)void supabaseClient.removeChannel(c)}},[refetch,realtime,table,enabled]);return{data,loading,error,refetch}}
export function useCurrentProfile(){const[data,setData]=useState<ProfileRow|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);const refetch=useCallback(async()=>{if(!supabaseClient){setError('Supabase yapılandırılmamış');setLoading(false);return}setLoading(true);const{data:{user},error:authError}=await supabaseClient.auth.getUser();if(authError||!user){setError(authError?.message||'Oturum bulunamadı');setLoading(false);return}const r=await supabaseClient.from('profiles').select('*').eq('id',user.id).single();setData((r.data||null) as ProfileRow|null);setError(r.error?.message||null);setLoading(false)},[]);useEffect(()=>{void refetch()},[refetch]);return{data,loading,error,refetch}}
export function useOpsData(options:{admin?:boolean}={}){const admin=options.admin??true;return{bankAccounts:useTable<BankAccount>('bank_accounts','updated_at',500,true),transactions:useTable<Tx>('transactions','occurred_at',500,true),paymentRequests:useTable<PaymentRequest>('payment_requests','created_at',300,true),auditLogs:useTable<AuditRow>('audit_logs','created_at',500,true),bankConnections:useTable<Connection>('bank_connections','created_at',300,true),accountMovements:useTable<Movement>('account_movements','occurred_at',500,true),accountHistory:useTable<History>('account_history','created_at',500,true),reconciliationItems:useTable<ReconciliationItem>('reconciliation_items','created_at',500,true),reconciliationMatches:useTable<ReconciliationMatch>('reconciliation_matches','matched_at',500,true),profiles:useTable<ProfileRow>('profiles','created_at',500,true,admin),userGroups:useTable<UserGroupRow>('user_groups','created_at',500,true,admin),userGroupMembers:useTable<UserGroupMemberRow>('user_group_members','created_at',1000,true,admin)}}
export type TransactionFilters={from?:string;to?:string;accountId?:string;min?:number;max?:number;direction?:string;status?:string;search?:string;page:number;pageSize:number}
export function useTransactionsPage(f:TransactionFilters){const[data,setData]=useState<Tx[]>([]),[count,setCount]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);const refetch=useCallback(async()=>{if(!supabaseClient){setError('Supabase yapılandırılmamış');setLoading(false);return}setLoading(true);let q=supabaseClient.from('transactions').select('*',{count:'exact'}).order('occurred_at',{ascending:false});if(f.from)q=q.gte('occurred_at',`${f.from}T00:00:00`);if(f.to)q=q.lte('occurred_at',`${f.to}T23:59:59.999`);if(f.accountId)q=q.eq('account_id',f.accountId);if(f.min!=null)q=q.gte('amount',f.min);if(f.max!=null)q=q.lte('amount',f.max);if(f.direction)q=q.eq('direction',f.direction);if(f.status)q=q.eq('status',f.status);if(f.search)q=q.ilike('counterparty',`%${f.search.replaceAll('%','')}%`);const from=f.page*f.pageSize;const r=await q.range(from,from+f.pageSize-1);setData((r.data||[]) as Tx[]);setCount(r.count||0);setError(r.error?.message||null);setLoading(false)},[f.from,f.to,f.accountId,f.min,f.max,f.direction,f.status,f.search,f.page,f.pageSize]);useEffect(()=>{void refetch();if(!supabaseClient)return;const c=supabaseClient.channel('transactions-page-live').on('postgres_changes',{event:'INSERT',schema:'public',table:'transactions'},()=>void refetch()).subscribe();return()=>{if(supabaseClient)void supabaseClient.removeChannel(c)}},[refetch]);return{data,count,loading,error,refetch}}
export type MovementFilters={from?:string;to?:string;accountId?:string;statuses:string[];search?:string;page:number;pageSize:number}
export function useMovementsPage(f:MovementFilters){const[data,setData]=useState<Movement[]>([]),[count,setCount]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);const refetch=useCallback(async()=>{if(!supabaseClient){setError('Supabase yapılandırılmamış');setLoading(false);return}setLoading(true);let q=supabaseClient.from('account_movements').select('*',{count:'exact'}).order('occurred_at',{ascending:false});if(f.from)q=q.gte('occurred_at',`${f.from}T00:00:00`);if(f.to)q=q.lte('occurred_at',`${f.to}T23:59:59.999`);if(f.accountId)q=q.eq('account_id',f.accountId);if(f.statuses.length)q=q.in('status',f.statuses);if(f.search)q=q.ilike('reference',`%${f.search.replaceAll('%','')}%`);const from=f.page*f.pageSize;const r=await q.range(from,from+f.pageSize-1);setData((r.data||[]) as Movement[]);setCount(r.count||0);setError(r.error?.message||null);setLoading(false)},[f.from,f.to,f.accountId,f.statuses.join(','),f.search,f.page,f.pageSize]);useEffect(()=>{void refetch();if(!supabaseClient)return;const c=supabaseClient.channel('movements-page-live').on('postgres_changes',{event:'INSERT',schema:'public',table:'account_movements'},()=>void refetch()).subscribe();return()=>{if(supabaseClient)void supabaseClient.removeChannel(c)}},[refetch]);return{data,count,loading,error,refetch}}
