import { FormEvent, useMemo, useState } from 'react'
import { NavLink } from 'react-router-dom'
import { Activity, BarChart3, Building2, ChevronRight, CircleDollarSign, Clock3, DatabaseZap, FileClock, FileText, Gauge, History, Link2, ListChecks, RefreshCw, Search, Settings, ShieldCheck, SlidersHorizontal, Users, WalletCards, Webhook, X, Plus, Download, Landmark, CircleAlert, CheckCircle2, PauseCircle, ArrowDownToLine, ArrowUpFromLine, Copy, Boxes, Filter, UserRoundCog } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { bankCatalog, bankByProvider } from '../lib/bankCatalog'
import { useOpsData } from '../lib/opsData'
import { cls, money, dt, Badge, PageState, Empty, Stat, copyText, SummaryStrip, TransactionTable } from '../components/ui/OperationsUi'

function AddBankModal({close,reload}:{close:()=>void;reload:()=>void}){const[code,setCode]=useState(bankCatalog[0]?.code||'');const[msg,setMsg]=useState('');const[saving,setSaving]=useState(false);async function submit(e:FormEvent){e.preventDefault();if(!supabase)return;const item=bankCatalog.find(x=>x.code===code);if(!item)return;setSaving(true);setMsg('');const {error}=await supabase.from('bank_connections').insert({provider:`tr:${item.code}`,institution_name:item.shortName,status:'pending',scopes:['accounts','balances','transactions']});if(error)setMsg(error.message);else{setMsg('Connection record created. Configure the licensed provider adapter, then start consent.');reload()}setSaving(false)}return <div className="ops-modalback" onMouseDown={e=>{if(e.currentTarget===e.target)close()}}><form className="ops-modal" onSubmit={submit}><div className="ops-modalhead"><div><h2>Add bank connection</h2><p>Create an institution entry for the Open Banking provider flow.</p></div><button type="button" onClick={close}><X size={17}/></button></div><label>Institution<select value={code} onChange={e=>setCode(e.target.value)}>{bankCatalog.map(b=><option key={b.code} value={b.code}>{b.shortName} · {b.category}</option>)}</select></label><div className="ops-callout"><ShieldCheck size={17}/><span>This form stores provider metadata only. Authentication must continue through the bank or licensed provider's consent page.</span></div>{msg&&<div className="ops-formmsg">{msg}</div>}<div className="ops-modalactions"><button type="button" className="ops-ghost" onClick={close}>Cancel</button><button className="ops-primary" disabled={saving}>{saving?'Creating…':'Add bank'}</button></div></form></div>}

export default function BankConnectionsPage(){const d=useOpsData();const[modal,setModal]=useState(false);const[msg,setMsg]=useState('');async function sync(id:string){if(!supabase)return;setMsg('');const {data,error}=await supabase.functions.invoke('bank-sync',{body:{connection_id:id}});setMsg(error?.message||data?.message||'Sync request sent');void d.reload()}return <div className="ops-page"><PageState loading={d.loading} error={d.error} reload={d.reload}/>{!d.loading&&!d.error&&<><div className="ops-pageactions"><div><h2>Provider registry</h2><p>Add institutions, inspect consent state and run authorized synchronization.</p></div><button className="ops-primary" onClick={()=>setModal(true)}><Plus size={15}/> Add bank</button></div>{msg&&<div className="ops-banner">{msg}</div>}<section className="ops-panel">{d.connections.length?<div className="ops-tablewrap"><table className="ops-table"><thead><tr><th>Provider</th><th>Institution</th><th>Status</th><th>Scopes</th><th>Last sync</th><th>Consent expiry</th><th></th></tr></thead><tbody>{d.connections.map(c=>{const catalog=bankByProvider(c.provider);return <tr key={c.id}><td><strong>{catalog?.shortName||c.provider}</strong><small>{c.provider}</small></td><td>{c.institution_name||catalog?.name||'—'}</td><td><Badge value={c.status}/></td><td>{(c.scopes||[]).join(', ')||'—'}</td><td>{dt(c.last_sync_at)}</td><td>{dt(c.consent_expires_at)}</td><td className="right"><button className="ops-small" onClick={()=>void sync(c.id)}><RefreshCw size={13}/> Sync</button></td></tr>})}</tbody></table></div>:<Empty title="No banks configured" detail="Use Add bank to build the provider registry. Live access begins only after an authorized provider adapter is configured."/>}</section>{modal&&<AddBankModal close={()=>setModal(false)} reload={d.reload}/>}</>}</div>}
