import { FormEvent, useMemo, useState } from 'react'
import { NavLink } from 'react-router-dom'
import { Activity, BarChart3, Building2, ChevronRight, CircleDollarSign, Clock3, DatabaseZap, FileClock, FileText, Gauge, History, Link2, ListChecks, RefreshCw, Search, Settings, ShieldCheck, SlidersHorizontal, Users, WalletCards, Webhook, X, Plus, Download, Landmark, CircleAlert, CheckCircle2, PauseCircle, ArrowDownToLine, ArrowUpFromLine, Copy, Boxes, Filter, UserRoundCog } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { bankCatalog, bankByProvider } from '../lib/bankCatalog'
import { useOpsData } from '../lib/opsData'
import { cls, money, dt, Badge, PageState, Empty, Stat, copyText, SummaryStrip, TransactionTable } from '../components/ui/OperationsUi'

export default function BankAccountsPage(){const d=useOpsData();const[q,setQ]=useState('');const[tab,setTab]=useState('all');const[bank,setBank]=useState('all');const statuses=[['all','All'],['active','Active'],['problem','Problems'],['suspended','Suspended'],['disabled','Disabled']];const banks=useMemo(()=>Array.from(new Set(d.accounts.map(a=>a.bank_name))).sort(),[d.accounts]);const rows=useMemo(()=>d.accounts.filter(a=>{const text=`${a.bank_name} ${a.account_name} ${a.iban_masked}`.toLowerCase();const status=String(a.status).toLowerCase();const tabOk=tab==='all'||(tab==='active'&&['active','connected'].includes(status))||(tab==='problem'&&['error','problem','blocked'].some(x=>status.includes(x)))||(tab==='suspended'&&status.includes('suspend'))||(tab==='disabled'&&['disabled','revoked','inactive'].some(x=>status.includes(x)));return text.includes(q.toLowerCase())&&tabOk&&(bank==='all'||a.bank_name===bank)}),[d.accounts,q,tab,bank]);return <div className="ops-page"><PageState loading={d.loading} error={d.error} reload={d.reload}/>{!d.loading&&!d.error&&<><SummaryStrip/><section className="ops-panel"><div className="ops-tabs">{statuses.map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}<span>{key==='all'?d.accounts.length:d.accounts.filter(a=>String(a.status).toLowerCase().includes(key==='problem'?'error':key)).length}</span></button>)}</div><div className="ops-filterbar"><label className="ops-search"><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search by name, IBAN…"/></label><select value={bank} onChange={e=>setBank(e.target.value)}><option value="all">All banks</option>{banks.map(b=><option key={b}>{b}</option>)}</select><button className="ops-ghost"><Boxes size={14}/> Groups</button><button className="ops-ghost"><Filter size={14}/> Tags</button><button className="ops-ghost" onClick={d.reload}><RefreshCw size={14}/> Refresh</button></div>{rows.length?<div className="ops-tablewrap"><table className="ops-table accounts"><thead><tr><th>Bank</th><th>Account name</th><th>IBAN</th><th className="right">Balance</th><th>Deposits</th><th>Withdrawals</th><th>Restrictions</th><th>Access</th></tr></thead><tbody>{rows.map(a=><tr key={a.id}><td><strong>{a.bank_name}</strong><small>{a.currency}</small></td><td>{a.account_name}</td><td><span className="ops-copy mono">{a.iban_masked}<button onClick={()=>copyText(a.iban_masked)}><Copy size={12}/></button></span></td><td className="right amount">{money(Number(a.balance),a.currency)}</td><td><Badge value={a.deposits_enabled}/></td><td><Badge value={a.withdrawals_enabled}/></td><td><Badge value={a.status}/></td><td><span className="ops-access"><span title="Deposits"><ArrowDownToLine size={15}/></span><span title="Withdrawals"><ArrowUpFromLine size={15}/></span></span></td></tr>)}</tbody></table></div>:<Empty title="No accounts match these filters" detail="Try another status, bank or search phrase."/>}</section></>}</div>}
