import { FormEvent, useMemo, useState } from 'react'
import { NavLink } from 'react-router-dom'
import { Activity, BarChart3, Building2, ChevronRight, CircleDollarSign, Clock3, DatabaseZap, FileClock, FileText, Gauge, History, Link2, ListChecks, RefreshCw, Search, Settings, ShieldCheck, SlidersHorizontal, Users, WalletCards, Webhook, X, Plus, Download, Landmark, CircleAlert, CheckCircle2, PauseCircle, ArrowDownToLine, ArrowUpFromLine, Copy, Boxes, Filter, UserRoundCog } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { bankCatalog, bankByProvider } from '../lib/bankCatalog'
import { useOpsData } from '../lib/opsData'
import { cls, money, dt, Badge, PageState, Empty, Stat, copyText, SummaryStrip, TransactionTable } from '../components/ui/OperationsUi'

export default function ConnectionStatusPage(){const d=useOpsData();const active=d.accounts.filter(a=>['active','connected'].includes(String(a.status).toLowerCase()));const suspended=d.accounts.filter(a=>String(a.status).toLowerCase().includes('suspend'));const disabled=d.accounts.filter(a=>['disabled','revoked','inactive','blocked','error'].some(x=>String(a.status).toLowerCase().includes(x)));return <div className="ops-page"><PageState loading={d.loading} error={d.error} reload={d.reload}/>{!d.loading&&!d.error&&<><div className="ops-statuscards"><div><CheckCircle2/><span><small>ACTIVE</small><strong>{active.length}</strong></span></div><div><PauseCircle/><span><small>SUSPENDED</small><strong>{suspended.length}</strong></span></div><div><CircleAlert/><span><small>DISABLED / ISSUES</small><strong>{disabled.length}</strong></span></div></div><section className="ops-panel"><div className="ops-panelhead"><div><h2>Status history</h2><p>Current account and provider state with last known update time.</p></div><button className="ops-ghost" onClick={d.reload}><RefreshCw size={14}/> Refresh</button></div>{d.accounts.length?<div className="ops-statuslist">{d.accounts.map(a=><div key={a.id}><ChevronRight size={16}/><span className="ops-banktag">{a.bank_name}</span><strong>{a.account_name}</strong><Badge value={a.status}/><span className="ops-spark">{Array.from({length:10},(_,i)=><i key={i} className={i%3===0?'bad':'good'}/>)}</span><small>{dt(a.updated_at)}</small></div>)}</div>:<Empty title="No account statuses" detail="Synchronized accounts will appear in this status center."/>}</section></>}</div>}
