import { FormEvent, useMemo, useState } from 'react'
import { NavLink } from 'react-router-dom'
import { Activity, BarChart3, Building2, ChevronRight, CircleDollarSign, Clock3, DatabaseZap, FileClock, FileText, Gauge, History, Link2, ListChecks, RefreshCw, Search, Settings, ShieldCheck, SlidersHorizontal, Users, WalletCards, Webhook, X, Plus, Download, Landmark, CircleAlert, CheckCircle2, PauseCircle, ArrowDownToLine, ArrowUpFromLine, Copy, Boxes, Filter, UserRoundCog } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { bankCatalog, bankByProvider } from '../lib/bankCatalog'
import { useOpsData } from '../lib/opsData'
import { cls, money, dt, Badge, PageState, Empty, Stat, copyText, SummaryStrip, TransactionTable } from '../components/ui/OperationsUi'

export default function DashboardPage(){const d=useOpsData();const total=d.accounts.reduce((s,a)=>s+Number(a.balance||0),0);const deposits=d.transactions.filter(t=>Number(t.amount)>0);const withdrawals=d.transactions.filter(t=>Number(t.amount)<0);const active=d.accounts.filter(a=>a.status==='active'||a.status==='connected').length;return <div className="ops-page"><PageState loading={d.loading} error={d.error} reload={d.reload}/>{!d.loading&&!d.error&&<><SummaryStrip/><div className="ops-stats"><Stat label="Total balance" value={money(total,d.accounts[0]?.currency||'TRY')} note={`${d.accounts.length} bank accounts`}/><Stat label="Active accounts" value={`${active}/${d.accounts.length}`} note="Current account state" tone="good"/><Stat label="Deposits" value={String(deposits.length)} note={`${money(deposits.reduce((s,t)=>s+Math.abs(Number(t.amount)),0),d.accounts[0]?.currency||'TRY')} loaded volume`} tone="good"/><Stat label="Withdrawals" value={String(withdrawals.length)} note={`${money(withdrawals.reduce((s,t)=>s+Math.abs(Number(t.amount)),0),d.accounts[0]?.currency||'TRY')} loaded volume`} tone="bad"/></div><div className="ops-grid2"><section className="ops-panel"><div className="ops-panelhead"><div><h2>Recent transactions</h2><p>Newest normalized ledger entries</p></div><NavLink className="ops-link" to="/transactions">View all <ChevronRight size={15}/></NavLink></div>{d.transactions.length?<TransactionTable rows={d.transactions.slice(0,8)} accounts={d.accounts}/>:<Empty title="No transaction data" detail="Authorized provider transactions will appear here after synchronization."/>}</section><section className="ops-panel"><div className="ops-panelhead"><div><h2>Account health</h2><p>Live bank account availability</p></div><NavLink className="ops-link" to="/connection-status">Status center <ChevronRight size={15}/></NavLink></div>{d.accounts.length?<div className="ops-health">{d.accounts.slice(0,10).map(a=><div key={a.id}><span className="ops-bankicon"><Landmark size={16}/></span><span className="grow"><strong>{a.bank_name}</strong><small>{a.account_name}</small></span><Badge value={a.status}/></div>)}</div>:<Empty title="No connected accounts" detail="Create a bank connection to start the provider onboarding flow."/>}</section></div></>}</div>}
