import { FormEvent, useMemo, useState } from 'react'
import { NavLink } from 'react-router-dom'
import { Activity, BarChart3, Building2, ChevronRight, CircleDollarSign, Clock3, DatabaseZap, FileClock, FileText, Gauge, History, Link2, ListChecks, RefreshCw, Search, Settings, ShieldCheck, SlidersHorizontal, Users, WalletCards, Webhook, X, Plus, Download, Landmark, CircleAlert, CheckCircle2, PauseCircle, ArrowDownToLine, ArrowUpFromLine, Copy, Boxes, Filter, UserRoundCog } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { bankCatalog, bankByProvider } from '../lib/bankCatalog'
import { useOpsData } from '../lib/opsData'
import { cls, money, dt, Badge, PageState, Empty, Stat, copyText, SummaryStrip, TransactionTable } from '../components/ui/OperationsUi'

export default function ReconciliationPage(){const d=useOpsData();return <div className="ops-page"><PageState loading={d.loading} error={d.error} reload={d.reload}/>{!d.loading&&!d.error&&<section className="ops-panel"><div className="ops-panelhead"><div><h2>Reconciliation</h2><p>Compare internal ledger and provider balances</p></div></div>{d.reconciliation.length?<div className="ops-tablewrap"><table className="ops-table"><thead><tr><th>Created</th><th>Account</th><th className="right">Ledger</th><th className="right">Bank</th><th className="right">Difference</th><th>Status</th></tr></thead><tbody>{d.reconciliation.map(r=>{const a=d.accounts.find(x=>x.id===r.account_id);return <tr key={r.id}><td>{dt(r.created_at)}</td><td>{a?.account_name||'—'}</td><td className="right">{money(Number(r.ledger_balance),a?.currency||'TRY')}</td><td className="right">{money(Number(r.bank_balance),a?.currency||'TRY')}</td><td className={cls('right amount',Number(r.difference)===0?'positive':'negative')}>{money(Number(r.difference),a?.currency||'TRY')}</td><td><Badge value={r.status}/></td></tr>})}</tbody></table></div>:<Empty title="Nothing to reconcile" detail="Reconciliation snapshots will appear here after provider balances are imported."/>}</section>}</div>}
