import { FormEvent, useMemo, useState } from 'react'
import { NavLink } from 'react-router-dom'
import { Activity, BarChart3, Building2, ChevronRight, CircleDollarSign, Clock3, DatabaseZap, FileClock, FileText, Gauge, History, Link2, ListChecks, RefreshCw, Search, Settings, ShieldCheck, SlidersHorizontal, Users, WalletCards, Webhook, X, Plus, Download, Landmark, CircleAlert, CheckCircle2, PauseCircle, ArrowDownToLine, ArrowUpFromLine, Copy, Boxes, Filter, UserRoundCog } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { bankCatalog, bankByProvider } from '../lib/bankCatalog'
import { useOpsData } from '../lib/opsData'
import { cls, money, dt, Badge, PageState, Empty, Stat, copyText, SummaryStrip, TransactionTable } from '../components/ui/OperationsUi'

export default function ReportsPage(){const d=useOpsData();const dep=d.transactions.filter(t=>Number(t.amount)>=0).reduce((s,t)=>s+Number(t.amount),0);const wd=d.transactions.filter(t=>Number(t.amount)<0).reduce((s,t)=>s+Math.abs(Number(t.amount)),0);return <div className="ops-page"><PageState loading={d.loading} error={d.error} reload={d.reload}/>{!d.loading&&!d.error&&<><div className="ops-stats"><Stat label="Gross deposits" value={money(dep)} note="Loaded transaction window" tone="good"/><Stat label="Gross withdrawals" value={money(wd)} note="Loaded transaction window" tone="bad"/><Stat label="Net flow" value={money(dep-wd)} note="Deposits minus withdrawals" tone={dep-wd>=0?'good':'bad'}/><Stat label="Reconciliation issues" value={String(d.reconciliation.filter(r=>Number(r.difference)!==0).length)} note="Non-zero differences" tone="warn"/></div><section className="ops-panel"><div className="ops-panelhead"><div><h2>Operational report</h2><p>Live summary generated from the currently loaded Supabase data.</p></div></div><div className="ops-reportgrid"><div><FileText size={20}/><strong>Transactions</strong><span>{d.transactions.length} records loaded</span></div><div><WalletCards size={20}/><strong>Accounts</strong><span>{d.accounts.length} synchronized accounts</span></div><div><Link2 size={20}/><strong>Connections</strong><span>{d.connections.length} provider records</span></div><div><ListChecks size={20}/><strong>Reconciliation</strong><span>{d.reconciliation.length} snapshots</span></div></div></section></>}</div>}
