import { createClient } from '@supabase/supabase-js'
const url=process.env.SUPABASE_URL;const key=process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY
if(!url||!key)throw new Error('SUPABASE_URL and backend Supabase key are required')
const db=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})
type Rule={id:string;user_id:string;name:string;from_account_id:string;to_account_id:string|null;condition:Record<string,unknown>;amount_type:'fixed'|'percent'|'all_above';amount_value:number;active:boolean}
async function audit(user_id:string,action:string,detail:string,severity:'info'|'success'|'warning'|'error'|'critical'='info'){const{error}=await db.from('audit_logs').insert({user_id,actor_label:'automation',action,resource_type:'rule_engine',detail,severity});if(error)console.error(error.message)}
function amountFor(rule:Rule,balance:number){if(rule.amount_type==='fixed')return Number(rule.amount_value);if(rule.amount_type==='percent')return Math.max(0,balance*(Number(rule.amount_value)/100));return Math.max(0,balance-Number(rule.amount_value))}
function conditionPasses(rule:Rule,balance:number){const c=rule.condition||{};if(typeof c.min_balance==='number'&&balance<=c.min_balance)return false;if(c.weekdays_only===true){const d=new Date().getUTCDay();if(d===0||d===6)return false}if(typeof c.day_of_month==='number'&&new Date().getUTCDate()!==c.day_of_month)return false;return true}
async function duplicate(userId:string,ruleId:string,accountId:string,amount:number){const since=new Date(Date.now()-3600000).toISOString();const{data,error}=await db.from('payment_requests').select('id').eq('user_id',userId).eq('account_id',accountId).eq('amount',amount).in('status',['pending_approval','approved']).gte('created_at',since).contains('metadata',{automation_rule_id:ruleId}).limit(1);if(error&&error.code!=='42703')throw error;return Boolean(data?.length)}
export async function runRuleEngine(){const{data,error}=await db.from('automation_rules').select('*').eq('active',true);if(error)throw error;const rules=(data||[]) as Rule[];let created=0
 for(const rule of rules){try{const{data:account,error:aerr}=await db.from('bank_accounts').select('id,user_id,balance,currency,status').eq('id',rule.from_account_id).eq('user_id',rule.user_id).maybeSingle();if(aerr||!account){await audit(rule.user_id,'rule_skipped',`${rule.name}: source account unavailable`,'warning');continue}const balance=Number(account.balance||0);if(!conditionPasses(rule,balance)){await audit(rule.user_id,'rule_skipped',`${rule.name}: condition not met`);continue}const amount=Number(amountFor(rule,balance).toFixed(2));if(amount<=0||amount>balance){await audit(rule.user_id,'rule_skipped',`${rule.name}: invalid calculated amount`,'warning');continue}const since=new Date(Date.now()-3600000).toISOString();const{data:dupes}=await db.from('payment_requests').select('id').eq('user_id',rule.user_id).eq('account_id',account.id).eq('amount',amount).in('status',['pending_approval','approved']).gte('created_at',since).limit(1);if(dupes?.length)continue
 const{data:req,error:rerr}=await db.from('payment_requests').insert({user_id:rule.user_id,requested_by:rule.user_id,account_id:account.id,direction:'transfer',amount,currency:account.currency,destination_name:rule.to_account_id?'Internal account':'Approval required',description:`Automation rule: ${rule.name}`,status:'pending_approval'}).select('id').single();if(rerr)throw rerr;created++;await db.from('automation_rules').update({last_run_at:new Date().toISOString()}).eq('id',rule.id);await audit(rule.user_id,'payment_request_created',`Rule ${rule.name} created approval request ${req.id}`,'success')
 }catch(e){await audit(rule.user_id,'rule_failed',e instanceof Error?e.message:String(e),'error')}}return{processed:rules.length,created}}
if(import.meta.url===`file://${process.argv[1]}`)runRuleEngine().catch(e=>{console.error(e);process.exit(1)})
