import { NavLink, Navigate, Route, Routes, useLocation } from 'react-router-dom'
import { useMemo, useState } from 'react'
import { Activity, BarChart3, Bell, ChevronRight, CircleDollarSign, FileClock, LayoutDashboard, ListChecks, LogOut, Search, Settings, ShieldCheck, SlidersHorizontal, Users, WalletCards } from 'lucide-react'
import { accounts, auditLogs, dailyReport, history, movements, reconciliationRows, transactions, users } from './data/mock'
import { AccountDrawer, TransactionDrawer } from './components/DetailDrawers'

const nav = [
  ['Dashboard', '/', LayoutDashboard], ['Bank Accounts', '/bank-accounts', WalletCards], ['Transactions', '/transactions', CircleDollarSign], ['Account Movements', '/account-movements', Activity], ['Account History', '/account-history', FileClock], ['Reports', '/reports', BarChart3], ['Reconciliation', '/reconciliation', ListChecks], ['Users', '/users', Users], ['Audit Log', '/audit-log', ShieldCheck], ['Settings', '/settings', Settings],
] as const

function Badge({ value }: { value: string }) { return <span className={`badge ${value.toLowerCase().replaceAll(' ', '-')}`}>{value}</span> }

function Shell({ children }: { children: React.ReactNode }) {
  const location = useLocation(); const [notices,setNotices]=useState(false)
  const title = nav.find((x) => x[1] === location.pathname)?.[0] ?? 'Fintech Panel'
  const authRoot=document.querySelector('[data-auth-role]') as HTMLElement|null
  const role=authRoot?.dataset.authRole || 'viewer'; const user=authRoot?.dataset.authUser || 'Administrator'
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark">F</div><div><strong>Fintech Panel</strong><span>Operations Console</span></div></div><nav>{nav.map(([label,href,Icon])=><NavLink key={href} to={href} end={href==='/' } className={({isActive})=>isActive?'nav-link active':'nav-link'}><Icon size={18}/><span>{label}</span></NavLink>)}</nav><div className="sidebar-foot"><button><LogOut size={17}/> Sign out</button></div></aside>
    <main className="content"><header className="topbar"><div><p>Administration / {role}</p><h1>{title}</h1></div><div className="top-actions"><div className="env-pill"><span className="live-dot"/> SANDBOX</div><button className="icon-btn" onClick={()=>setNotices(v=>!v)}><Bell size={17}/><i>3</i></button><div className="admin-chip"><div className="avatar">{user.slice(0,2).toUpperCase()}</div><div><strong>{user}</strong><span>{role}</span></div></div></div></header>
    {notices&&<div className="notification-pop"><div className="notification-head"><strong>Operations center</strong><span>3 new</span></div><div className="notice"><b>Reconciliation variance</b><span>One sandbox account requires review.</span><small>2 min ago</small></div><div className="notice"><b>Account health changed</b><span>Sandbox connection entered review state.</span><small>18 min ago</small></div><div className="notice"><b>Daily report ready</b><span>Operations summary is available.</span><small>1 hr ago</small></div></div>}{children}</main>
  </div>
}
function Stat({label,value,note}:{label:string;value:string;note:string}){return <div className="stat-card"><span>{label}</span><strong>{value}</strong><small>{note}</small></div>}
function SearchBox({value,onChange,placeholder}:{value:string;onChange:(v:string)=>void;placeholder:string}){return <label className="search-box"><Search size={15}/><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
function Dashboard(){const total=accounts.reduce((s,a)=>s+a.balance,0);const incoming=transactions.filter(t=>t.amount>0).reduce((s,t)=>s+t.amount,0);return <div className="page"><div className="hero-strip"><div><span className="hero-kicker">CONTROL ROOM</span><h2>Operational overview</h2><p>Monitor the health of your sandbox financial workspace from one command surface.</p></div><div className="hero-score"><span>System health</span><strong>98.7%</strong><small>All core services operational</small></div></div><div className="stats-grid"><Stat label="Total balance" value={`₺${total.toLocaleString('tr-TR',{minimumFractionDigits:2})}`} note="Across sandbox accounts"/><Stat label="Connected accounts" value="3" note="2 active, 1 suspended"/><Stat label="Incoming volume" value={`₺${incoming.toLocaleString('tr-TR')}`} note="Visible sandbox ledger"/><Stat label="Pending review" value="1" note="Requires operator review"/></div><div className="two-col"><section className="panel"><div className="panel-head"><div><h2>Recent transactions</h2><p>Latest sandbox account activity</p></div><NavLink to="/transactions" className="text-link">View all <ChevronRight size={16}/></NavLink></div><TransactionTable compact/></section><section className="panel"><div className="panel-head"><div><h2>Account health</h2><p>Current operational state</p></div></div><div className="health-list">{accounts.map(a=><div className="health-row" key={a.id}><div><strong>{a.bank}</strong><span>{a.name}</span></div><Badge value={a.status}/></div>)}</div></section></div></div>}
function Accounts(){const[selected,setSelected]=useState<(typeof accounts)[number]|null>(null);return <><div className="page"><section className="panel"><div className="panel-head"><div><h2>Bank accounts</h2><p>Connected sandbox accounts and operational state</p></div><button className="primary-btn">Add sandbox account</button></div><div className="table-wrap"><table><thead><tr><th>Bank</th><th>Account name</th><th>IBAN</th><th>Balance</th><th>Deposits</th><th>Withdrawals</th><th>Status</th></tr></thead><tbody>{accounts.map(a=><tr key={a.id} className="clickable-row" onClick={()=>setSelected(a)}><td><strong>{a.bank}</strong></td><td>{a.name}</td><td className="mono">{a.iban}</td><td className="amount">₺{a.balance.toLocaleString('tr-TR',{minimumFractionDigits:2})}</td><td><Badge value={a.deposits?'Enabled':'Disabled'}/></td><td><Badge value={a.withdrawals?'Enabled':'Disabled'}/></td><td><Badge value={a.status}/></td></tr>)}</tbody></table></div></section></div><AccountDrawer account={selected} onClose={()=>setSelected(null)}/></>}
function TransactionTable({compact=false,rows=transactions,onSelect}:{compact?:boolean;rows?:typeof transactions;onSelect?:(t:(typeof transactions)[number])=>void}){const data=compact?rows.slice(0,3):rows;return <div className="table-wrap"><table><thead><tr><th>Date</th><th>Type</th><th>Transfer</th><th>Counterparty</th><th>Account</th><th>Bank</th><th>Amount</th><th>Balance after</th><th>Status</th></tr></thead><tbody>{data.map(t=><tr key={t.id} className={onSelect?'clickable-row':''} onClick={()=>onSelect?.(t)}><td>{t.date}</td><td>{t.type}</td><td>{t.method}</td><td><div>{t.counterparty}</div><small className="mono">{t.iban}</small></td><td>{t.account}</td><td>{t.bank}</td><td className={t.amount<0?'amount negative':'amount positive'}>{t.amount<0?'-':'+'}₺{Math.abs(t.amount).toLocaleString('tr-TR')}</td><td className="amount">₺{t.balanceAfter.toLocaleString('tr-TR',{minimumFractionDigits:2})}</td><td><Badge value={t.status}/></td></tr>)}</tbody></table></div>}
function Transactions(){const[query,setQuery]=useState('');const[selected,setSelected]=useState<(typeof transactions)[number]|null>(null);const rows=useMemo(()=>transactions.filter(t=>Object.values(t).join(' ').toLowerCase().includes(query.toLowerCase())),[query]);return <><div className="page"><section className="panel"><div className="panel-head"><div><h2>Transactions</h2><p>Searchable sandbox transaction ledger. Click a row for full details.</p></div><div className="toolbar"><SearchBox value={query} onChange={setQuery} placeholder="Search transaction..."/><button className="secondary-btn"><SlidersHorizontal size={14}/> Filters</button></div></div><TransactionTable rows={rows} onSelect={setSelected}/><div className="table-foot">Showing {rows.length} of {transactions.length} records</div></section></div><TransactionDrawer transaction={selected} onClose={()=>setSelected(null)}/></>}
function Movements(){const[query,setQuery]=useState('');const rows=useMemo(()=>movements.filter(m=>Object.values(m).join(' ').toLowerCase().includes(query.toLowerCase())),[query]);return <div className="page"><section className="panel"><div className="panel-head"><div><h2>Account movements</h2><p>Normalized feed events from connected sandbox accounts</p></div><SearchBox value={query} onChange={setQuery} placeholder="Search movements..."/></div><div className="table-wrap"><table><thead><tr><th>Time</th><th>Movement</th><th>Account</th><th>Reference</th><th>Source</th><th>Amount</th><th>Running balance</th><th>Status</th></tr></thead><tbody>{rows.map(m=><tr key={m.id}><td>{m.time}</td><td>{m.kind}</td><td><strong>{m.bank}</strong><small className="subline">{m.account}</small></td><td className="mono">{m.reference}</td><td>{m.source}</td><td className={m.amount<0?'amount negative':m.amount>0?'amount positive':'amount'}>{m.amount===0?'—':`${m.amount<0?'-':'+'}₺${Math.abs(m.amount).toLocaleString('tr-TR')}`}</td><td className="amount">₺{m.runningBalance.toLocaleString('tr-TR',{minimumFractionDigits:2})}</td><td><Badge value={m.status}/></td></tr>)}</tbody></table></div></section></div>}
function History(){return <div className="page"><section className="panel"><div className="panel-head"><div><h2>Account history</h2><p>Operational state changes and system events</p></div></div><div className="timeline">{history.map((h,i)=><div className="timeline-item" key={i}><div className="dot"/><div><div className="timeline-top"><strong>{h.bank} · {h.account}</strong><Badge value={h.status}/></div><p>{h.event}</p><small>{h.time}</small></div></div>)}</div></section></div>}
function Reports(){const max=Math.max(...dailyReport.filter(x=>typeof x.value==='number').map(x=>Math.abs(x.value as number)),1);return <div className="page"><div className="stats-grid">{dailyReport.map(r=><Stat key={r.label} label={r.label} value={typeof r.value==='number'&&r.label!=='Matched reconciliation'?`₺${r.value.toLocaleString('tr-TR')}`:String(r.value)} note={r.change}/>)}</div><section className="panel"><div className="panel-head"><div><h2>Daily operations report</h2><p>Sandbox volume overview</p></div><button className="secondary-btn">Export preview</button></div><div className="bar-list">{dailyReport.slice(0,3).map(r=><div className="bar-row" key={r.label}><div className="bar-meta"><span>{r.label}</span><strong>{r.value}</strong></div><div className="bar-track"><div className="bar-fill" style={{width:`${Math.max(8,Math.abs(Number(r.value))/max*100)}%`}}/></div></div>)}</div></section></div>}
function Reconciliation(){const matched=reconciliationRows.filter(r=>r.status==='matched').length;return <div className="page"><div className="stats-grid compact-stats"><Stat label="Accounts checked" value={String(reconciliationRows.length)} note="Latest sandbox run"/><Stat label="Matched" value={String(matched)} note="No variance"/><Stat label="Investigate" value={String(reconciliationRows.length-matched)} note="Variance detected"/><Stat label="Total variance" value={`₺${reconciliationRows.reduce((s,r)=>s+Math.abs(r.difference),0).toFixed(2)}`} note="Across all accounts"/></div><section className="panel"><div className="panel-head"><div><h2>Reconciliation</h2><p>Ledger balance compared with sandbox bank balance</p></div><button className="primary-btn">Run sandbox check</button></div><div className="table-wrap"><table><thead><tr><th>Account</th><th>Bank</th><th>Ledger balance</th><th>Bank balance</th><th>Difference</th><th>Checked at</th><th>Status</th></tr></thead><tbody>{reconciliationRows.map(r=><tr key={r.id}><td>{r.account}</td><td>{r.bank}</td><td className="amount">₺{r.ledgerBalance.toLocaleString('tr-TR',{minimumFractionDigits:2})}</td><td className="amount">₺{r.bankBalance.toLocaleString('tr-TR',{minimumFractionDigits:2})}</td><td className={r.difference?'amount negative':'amount positive'}>₺{r.difference.toFixed(2)}</td><td>{r.checkedAt}</td><td><Badge value={r.status}/></td></tr>)}</tbody></table></div></section></div>}
function UsersPage(){return <div className="page"><section className="panel"><div className="panel-head"><div><h2>Users</h2><p>Administration roles and access status</p></div><button className="primary-btn">Invite sandbox user</button></div><div className="table-wrap"><table><thead><tr><th>User</th><th>Email</th><th>Role</th><th>Group</th><th>Last seen</th><th>Status</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><strong>{u.name}</strong><small className="subline mono">{u.id}</small></td><td>{u.email}</td><td><Badge value={u.role}/></td><td>{u.group}</td><td>{u.lastSeen}</td><td><Badge value={u.status}/></td></tr>)}</tbody></table></div></section></div>}
function AuditLog(){return <div className="page"><section className="panel"><div className="panel-head"><div><h2>Audit log</h2><p>Operator and system events</p></div><button className="secondary-btn">Download CSV preview</button></div><div className="audit-list">{auditLogs.map(log=><div className="audit-row" key={log.id}><div className={`severity-dot ${log.severity}`}/><div className="audit-main"><div><strong>{log.action}</strong><span>{log.detail}</span></div><div className="audit-meta"><span>{log.actor}</span><span>{log.resource}</span><span>{log.time}</span><code>{log.id}</code></div></div></div>)}</div></section></div>}
function SettingsPage(){return <div className="page"><div className="settings-grid"><section className="panel settings-card"><div className="panel-head"><div><h2>Environment</h2><p>Runtime configuration preview</p></div></div><div className="setting-row"><div><strong>Mode</strong><span>Sandbox only</span></div><Badge value="Active"/></div><div className="setting-row"><div><strong>Supabase</strong><span>Connected workspace</span></div><Badge value="Configured"/></div><div className="setting-row"><div><strong>Bank adapters</strong><span>Official API adapters only</span></div><Badge value="Sandbox"/></div></section><section className="panel settings-card"><div className="panel-head"><div><h2>Notifications</h2><p>Operator alert preferences</p></div></div>{['Account status changes','Reconciliation variance','Manual review events'].map(x=><label className="toggle-row" key={x}><span>{x}</span><input type="checkbox" defaultChecked/></label>)}</section></div></div>}
export default function App(){return <Shell><Routes><Route path="/" element={<Dashboard/>}/><Route path="/bank-accounts" element={<Accounts/>}/><Route path="/transactions" element={<Transactions/>}/><Route path="/account-movements" element={<Movements/>}/><Route path="/account-history" element={<History/>}/><Route path="/reports" element={<Reports/>}/><Route path="/reconciliation" element={<Reconciliation/>}/><Route path="/users" element={<UsersPage/>}/><Route path="/audit-log" element={<AuditLog/>}/><Route path="/settings" element={<SettingsPage/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes></Shell>}
