import { NavLink, Navigate, Route, Routes, useLocation } from 'react-router-dom'
import { useMemo, useState } from 'react'
import { Activity, BarChart3, Bell, Building2, ChevronRight, CircleDollarSign, FileClock, LayoutDashboard, Link2, ListChecks, LogOut, RefreshCw, Search, Settings, ShieldCheck, SlidersHorizontal, Users, WalletCards } from 'lucide-react'
import { useOpsData, type BankAccount, type Tx } from './lib/opsData'

const nav = [
  ['Dashboard','/',LayoutDashboard],['Bank Connections','/bank-connections',Link2],['Bank Accounts','/bank-accounts',WalletCards],['Transactions','/transactions',CircleDollarSign],['Account Movements','/account-movements',Activity],['Account History','/account-history',FileClock],['Reports','/reports',BarChart3],['Reconciliation','/reconciliation',ListChecks],['Users','/users',Users],['Audit Log','/audit-log',ShieldCheck],['Settings','/settings',Settings],
] as const

function Badge({value}:{value:string}){return <span className={`badge ${String(value).toLowerCase().replaceAll(' ','-')}`}>{value}</span>}
function money(v:number,c='TRY'){return new Intl.NumberFormat('tr-TR',{style:'currency',currency:c,maximumFractionDigits:2}).format(Number(v||0))}
function Empty({title,detail}:{title:string;detail:string}){return <div className="live-empty"><Building2 size={28}/><strong>{title}</strong><span>{detail}</span></div>}

function Shell({children}:{children:React.ReactNode}){
 const location=useLocation(); const[notices,setNotices]=useState(false)
 const title=nav.find(x=>x[1]===location.pathname)?.[0]??'Fintech Panel'
 const authRoot=document.querySelector('[data-auth-role]') as HTMLElement|null
 const role=authRoot?.dataset.authRole||'viewer'; const user=authRoot?.dataset.authUser||'Administrator'
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">F</div><div><strong>Fintech Panel</strong><span>Operations Console</span></div></div><nav>{nav.map(([label,href,Icon])=><NavLink key={href} to={href} end={href==='/' } className={({isActive})=>isActive?'nav-link active':'nav-link'}><Icon size={18}/><span>{label}</span></NavLink>)}</nav><div className="sidebar-foot"><button><LogOut size={17}/> Sign out</button></div></aside><main className="content"><header className="topbar"><div><p>Administration / {role}</p><h1>{title}</h1></div><div className="top-actions"><div className="env-pill"><span className="live-dot"/> LIVE DATA</div><button className="icon-btn" onClick={()=>setNotices(v=>!v)}><Bell size={17}/></button><div className="admin-chip"><div className="avatar">{user.slice(0,2).toUpperCase()}</div><div><strong>{user}</strong><span>{role}</span></div></div></div></header>{notices&&<div className="notification-pop"><div className="notification-head"><strong>Operations center</strong><span>live</span></div><div className="notice"><b>Live mode enabled</b><span>Pages now read directly from Supabase tables.</span></div></div>}{children}</main></div>
}

function PageState({loading,error,reload}:{loading:boolean;error:string|null;reload:()=>void}){if(loading)return <div className="live-state"><div className="boot-loader"/><span>Loading live operations data…</span></div>;if(error)return <div className="live-error"><strong>Live data error</strong><span>{error}</span><button className="secondary-btn" onClick={reload}><RefreshCw size={14}/> Retry</button></div>;return null}

function Dashboard(){const d=useOpsData();const total=d.accounts.reduce((s,a)=>s+Number(a.balance),0);const incoming=d.transactions.filter(t=>t.direction==='deposit'||Number(t.amount)>0).reduce((s,t)=>s+Math.abs(Number(t.amount)),0);return <div className="page"><PageState loading={d.loading} error={d.error} reload={d.reload}/>{!d.loading&&!d.error&&<><div className="hero-strip"><div><span className="hero-kicker">LIVE CONTROL ROOM</span><h2>Operational overview</h2><p>Balances, accounts and transaction activity are read directly from the Supabase operations database.</p></div><div className="hero-score"><span>Connections</span><strong>{d.connections.filter(x=>x.status==='connected'||x.status==='active').length}/{d.connections.length}</strong><small>Official-provider registry</small></div></div><div className="stats-grid"><Stat label="Total balance" value={money(total,d.accounts[0]?.currency||'TRY')} note={`${d.accounts.length} live accounts`}/><Stat label="Transactions" value={String(d.transactions.length)} note="Most recent 200 records"/><Stat label="Incoming volume" value={money(incoming,d.accounts[0]?.currency||'TRY')} note="Loaded transaction window"/><Stat label="Connections" value={String(d.connections.length)} note="Official API connections"/></div><div className="two-col"><section className="panel"><div className="panel-head"><div><h2>Recent transactions</h2><p>Live database activity</p></div><NavLink to="/transactions" className="text-link">View all <ChevronRight size={16}/></NavLink></div><TxTable rows={d.transactions.slice(0,5)} accounts={d.accounts}/></section><section className="panel"><div className="panel-head"><div><h2>Account health</h2><p>Current live account state</p></div></div>{d.accounts.length?<div className="health-list">{d.accounts.map(a=><div className="health-row" key={a.id}><div><strong>{a.bank_name}</strong><span>{a.account_name}</span></div><Badge value={a.status}/></div>)}</div>:<Empty title="No live accounts" detail="Connect an official Open Banking provider to begin syncing accounts."/>}</section></div></>}</div>}
function Stat({label,value,note}:{label:string;value:string;note:string}){return <div className="stat-card"><span>{label}</span><strong>{value}</strong><small>{note}</small></div>}

function Connections(){const d=useOpsData();return <div className="page"><PageState loading={d.loading} error={d.error} reload={d.reload}/>{!d.loading&&!d.error&&<section className="panel"><div className="panel-head"><div><h2>Bank connections</h2><p>Consent-based connections through official Open Banking / PSD2 providers.</p></div><button className="secondary-btn" disabled><Link2 size={14}/> Provider configuration required</button></div>{d.connections.length?<div className="table-wrap"><table><thead><tr><th>Provider</th><th>Institution</th><th>Status</th><th>Scopes</th><th>Last sync</th><th>Consent expiry</th></tr></thead><tbody>{d.connections.map(c=><tr key={c.id}><td><strong>{c.provider}</strong></td><td>{c.institution_name||'—'}</td><td><Badge value={c.status}/></td><td>{c.scopes.join(', ')}</td><td>{c.last_sync_at?new Date(c.last_sync_at).toLocaleString():'Never'}</td><td>{c.consent_expires_at?new Date(c.consent_expires_at).toLocaleString():'—'}</td></tr>)}</tbody></table></div>:<Empty title="No provider connected" detail="This workspace is ready for an official OAuth/Open Banking provider. Bank credentials, PINs and OTPs are not stored here."/>}</section>}</div>}

function Accounts(){const d=useOpsData();return <div className="page"><PageState loading={d.loading} error={d.error} reload={d.reload}/>{!d.loading&&!d.error&&<section className="panel"><div className="panel-head"><div><h2>Bank accounts</h2><p>Live records synced from authorized provider connections.</p></div><button className="secondary-btn" onClick={d.reload}><RefreshCw size={14}/> Refresh</button></div>{d.accounts.length?<div className="table-wrap"><table><thead><tr><th>Bank</th><th>Account</th><th>IBAN</th><th>Currency</th><th>Balance</th><th>Deposits</th><th>Withdrawals</th><th>Status</th></tr></thead><tbody>{d.accounts.map(a=><tr key={a.id}><td><strong>{a.bank_name}</strong></td><td>{a.account_name}</td><td className="mono">{a.iban_masked}</td><td>{a.currency}</td><td className="amount">{money(Number(a.balance),a.currency)}</td><td><Badge value={a.deposits_enabled?'Enabled':'Disabled'}/></td><td><Badge value={a.withdrawals_enabled?'Enabled':'Disabled'}/></td><td><Badge value={a.status}/></td></tr>)}</tbody></table></div>:<Empty title="No live bank accounts" detail="Account rows will appear after an authorized provider sync."/>}</section>}</div>}

function TxTable({rows,accounts}:{rows:Tx[];accounts:BankAccount[]}){const bank=(id:string|null)=>accounts.find(a=>a.id===id);return <div className="table-wrap"><table><thead><tr><th>Time</th><th>Direction</th><th>Method</th><th>Counterparty</th><th>Account</th><th>Amount</th><th>Balance after</th><th>Status</th></tr></thead><tbody>{rows.map(t=>{const a=bank(t.account_id);return <tr key={t.id}><td>{new Date(t.occurred_at).toLocaleString()}</td><td>{t.direction}</td><td>{t.method}</td><td><div>{t.counterparty||'—'}</div><small className="mono">{t.counterparty_iban_masked||''}</small></td><td>{a?.account_name||'—'}<small className="subline">{a?.bank_name||''}</small></td><td className={Number(t.amount)<0?'amount negative':'amount positive'}>{money(Number(t.amount),a?.currency||'TRY')}</td><td className="amount">{t.balance_after==null?'—':money(Number(t.balance_after),a?.currency||'TRY')}</td><td><Badge value={t.status}/></td></tr>})}</tbody></table></div>}
function Transactions(){const d=useOpsData();const[q,setQ]=useState('');const rows=useMemo(()=>d.transactions.filter(t=>Object.values(t).join(' ').toLowerCase().includes(q.toLowerCase())),[d.transactions,q]);return <div className="page"><PageState loading={d.loading} error={d.error} reload={d.reload}/>{!d.loading&&!d.error&&<section className="panel"><div className="panel-head"><div><h2>Transactions</h2><p>Live transaction ledger from Supabase.</p></div><div className="toolbar"><label className="search-box"><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search transactions…"/></label><button className="secondary-btn"><SlidersHorizontal size={14}/> Filters</button></div></div>{rows.length?<TxTable rows={rows} accounts={d.accounts}/>:<Empty title="No live transactions" detail="Provider-synced transaction records will appear here."/>}</section>}</div>}

function Movements(){const d=useOpsData();return <div className="page"><PageState loading={d.loading} error={d.error} reload={d.reload}/>{!d.loading&&!d.error&&<section className="panel"><div className="panel-head"><div><h2>Account movements</h2><p>Live normalized account events.</p></div></div>{d.movements.length?<div className="table-wrap"><table><thead><tr><th>Time</th><th>Type</th><th>Reference</th><th>Source</th><th>Amount</th><th>Running balance</th><th>Status</th></tr></thead><tbody>{d.movements.map(m=><tr key={m.id}><td>{new Date(m.occurred_at).toLocaleString()}</td><td>{m.movement_type}</td><td className="mono">{m.reference||'—'}</td><td>{m.source}</td><td className="amount">{Number(m.amount).toLocaleString('tr-TR')}</td><td className="amount">{m.running_balance==null?'—':Number(m.running_balance).toLocaleString('tr-TR')}</td><td><Badge value={m.status}/></td></tr>)}</tbody></table></div>:<Empty title="No live movements" detail="Normalized bank events will appear after provider synchronization."/>}</section>}</div>}
function History(){const d=useOpsData();return <div className="page"><PageState loading={d.loading} error={d.error} reload={d.reload}/>{!d.loading&&!d.error&&<section className="panel"><div className="panel-head"><div><h2>Account history</h2><p>Live operational history.</p></div></div>{d.history.length?<div className="timeline">{d.history.map(h=><div className="timeline-item" key={h.id}><div className="dot"/><div><div className="timeline-top"><strong>{h.event_type}</strong><Badge value={h.status}/></div><p>{h.event_message}</p><small>{new Date(h.created_at).toLocaleString()}</small></div></div>)}</div>:<Empty title="No account history" detail="Operational state changes will be recorded here."/>}</section>}</div>}
function Reports(){const d=useOpsData();const deposits=d.transactions.filter(t=>t.direction==='deposit').reduce((s,t)=>s+Math.abs(Number(t.amount)),0);const withdrawals=d.transactions.filter(t=>t.direction==='withdrawal').reduce((s,t)=>s+Math.abs(Number(t.amount)),0);return <div className="page"><PageState loading={d.loading} error={d.error} reload={d.reload}/>{!d.loading&&!d.error&&<><div className="stats-grid"><Stat label="Deposit volume" value={money(deposits)} note="Loaded live window"/><Stat label="Withdrawal volume" value={money(withdrawals)} note="Loaded live window"/><Stat label="Accounts" value={String(d.accounts.length)} note="Live rows"/><Stat label="Connections" value={String(d.connections.length)} note="Official-provider registry"/></div><section className="panel"><Empty title="Live reporting enabled" detail="Metrics above are calculated from current database rows, not mock data."/></section></>}</div>}
function Reconciliation(){const d=useOpsData();return <div className="page"><PageState loading={d.loading} error={d.error} reload={d.reload}/>{!d.loading&&!d.error&&<section className="panel"><div className="panel-head"><div><h2>Reconciliation</h2><p>Live stored reconciliation results.</p></div></div>{d.reconciliation.length?<div className="table-wrap"><table><thead><tr><th>Created</th><th>Ledger</th><th>Bank</th><th>Difference</th><th>Status</th></tr></thead><tbody>{d.reconciliation.map(r=><tr key={r.id}><td>{new Date(r.created_at).toLocaleString()}</td><td>{Number(r.ledger_balance).toLocaleString('tr-TR')}</td><td>{Number(r.bank_balance).toLocaleString('tr-TR')}</td><td>{Number(r.difference).toLocaleString('tr-TR')}</td><td><Badge value={r.status}/></td></tr>)}</tbody></table></div>:<Empty title="No reconciliation results" detail="Provider balance snapshots can be reconciled against your internal ledger here."/>}</section>}</div>}
function UsersPage(){const d=useOpsData();return <div className="page"><PageState loading={d.loading} error={d.error} reload={d.reload}/>{!d.loading&&!d.error&&<section className="panel"><div className="panel-head"><div><h2>Users</h2><p>Live profiles from Supabase Auth.</p></div></div><div className="table-wrap"><table><thead><tr><th>Name</th><th>Role</th><th>Created</th></tr></thead><tbody>{d.profiles.map(p=><tr key={p.id}><td><strong>{p.full_name||'Unnamed user'}</strong><small className="subline mono">{p.id}</small></td><td><Badge value={p.role}/></td><td>{new Date(p.created_at).toLocaleString()}</td></tr>)}</tbody></table></div></section>}</div>}
function AuditLog(){const d=useOpsData();return <div className="page"><PageState loading={d.loading} error={d.error} reload={d.reload}/>{!d.loading&&!d.error&&<section className="panel"><div className="panel-head"><div><h2>Audit log</h2><p>Live operator and system events.</p></div></div>{d.auditLogs.length?<div className="audit-list">{d.auditLogs.map(x=><div className="audit-row" key={x.id}><div className={`severity-dot ${x.severity}`}/><div className="audit-main"><div><strong>{x.action}</strong><span>{x.detail||''}</span></div><div className="audit-meta"><span>{x.actor_label||'system'}</span><span>{x.resource_type||''}</span><span>{new Date(x.created_at).toLocaleString()}</span><code>{x.id}</code></div></div></div>)}</div>:<Empty title="No audit events" detail="Admin and system activity can be logged here."/>}</section>}</div>}
function SettingsPage(){const d=useOpsData();return <div className="page"><PageState loading={d.loading} error={d.error} reload={d.reload}/>{!d.loading&&!d.error&&<div className="settings-grid"><section className="panel settings-card"><div className="panel-head"><div><h2>Environment</h2><p>Runtime configuration</p></div></div><div className="setting-row"><div><strong>Database</strong><span>Supabase live</span></div><Badge value="Active"/></div><div className="setting-row"><div><strong>Data source</strong><span>Mock data disabled in AppLive</span></div><Badge value="Live"/></div><div className="setting-row"><div><strong>Bank access</strong><span>Official OAuth/Open Banking providers only</span></div><Badge value="Protected"/></div></section><section className="panel settings-card"><div className="panel-head"><div><h2>Provider policy</h2><p>Security boundary</p></div></div><div className="setting-row"><div><strong>Credentials</strong><span>Never stored</span></div><Badge value="Protected"/></div><div className="setting-row"><div><strong>PIN / OTP</strong><span>Provider-hosted SCA only</span></div><Badge value="Protected"/></div></section></div>}</div>}
export default function AppLive(){return <Shell><Routes><Route path="/" element={<Dashboard/>}/><Route path="/bank-connections" element={<Connections/>}/><Route path="/bank-accounts" element={<Accounts/>}/><Route path="/transactions" element={<Transactions/>}/><Route path="/account-movements" element={<Movements/>}/><Route path="/account-history" element={<History/>}/><Route path="/reports" element={<Reports/>}/><Route path="/reconciliation" element={<Reconciliation/>}/><Route path="/users" element={<UsersPage/>}/><Route path="/audit-log" element={<AuditLog/>}/><Route path="/settings" element={<SettingsPage/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes></Shell>}
