import { useCallback, useEffect, useState } from 'react'
import { ArrowLeft, Check, Play, RefreshCw, X } from 'lucide-react'
import { Link } from 'react-router-dom'
import { supabase } from './lib/supabase'
import type { Audit, BankAccount, PaymentRequest, Tx } from './lib/opsData'

type Toast={id:number;text:string;kind:'ok'|'error'}
const money=(v:number,c:string)=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:c}).format(v)

export default function AutomationCenter(){
 const [accounts,setAccounts]=useState<BankAccount[]>([]),[payments,setPayments]=useState<PaymentRequest[]>([]),[logs,setLogs]=useState<Audit[]>([]),[txs,setTxs]=useState<Tx[]>([])
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState<string|null>(null),[toasts,setToasts]=useState<Toast[]>([])
 const toast=(text:string,kind:'ok'|'error'='ok')=>{const id=Date.now();setToasts(v=>[...v,{id,text,kind}]);setTimeout(()=>setToasts(v=>v.filter(x=>x.id!==id)),3500)}
 const load=useCallback(async()=>{if(!supabase)return;setLoading(true);const [a,p,l,t]=await Promise.all([supabase.from('bank_accounts').select('*').order('updated_at',{ascending:false}),supabase.from('payment_requests').select('*').order('created_at',{ascending:false}).limit(100),supabase.from('audit_logs').select('*').order('created_at',{ascending:false}).limit(100),supabase.from('transactions').select('*').order('occurred_at',{ascending:false}).limit(100)]);const error=a.error||p.error||l.error||t.error;if(error)toast(error.message,'error');setAccounts((a.data||[]) as BankAccount[]);setPayments((p.data||[]) as PaymentRequest[]);setLogs((l.data||[]) as Audit[]);setTxs((t.data||[]) as Tx[]);setLoading(false)},[])
 useEffect(()=>{void load();if(!supabase)return;const client=supabase;const ch=client.channel('automation-center').on('postgres_changes',{event:'*',schema:'public',table:'payment_requests'},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'audit_logs'},()=>void load()).subscribe((status,err)=>{if(status==='CHANNEL_ERROR'||status==='TIMED_OUT')toast(err?.message||`Realtime: ${status}`,'error')});return()=>{void client.removeChannel(ch)}},[load])
 async function decide(id:string,status:'approved'|'rejected'){if(!supabase)return;setBusy(id);const {data:{user}}=await supabase.auth.getUser();const patch=status==='approved'?{status,approved_by:user?.id||null,approved_at:new Date().toISOString(),updated_at:new Date().toISOString()}:{status,approved_by:null,approved_at:null,updated_at:new Date().toISOString()};const {error}=await supabase.from('payment_requests').update(patch).eq('id',id).eq('status','pending_approval');setBusy(null);if(error)toast(error.message,'error');else{toast(status==='approved'?'Talep onaylandı. Bankaya işlem gönderilmedi.':'Talep reddedildi.');void load()}}
 async function dispatch(){if(!supabase)return;setBusy('dispatch');const {data,error}=await supabase.functions.invoke('automation-dispatch',{body:{}});setBusy(null);if(error)toast(error.message,'error');else toast(data?.message||'Automation queued')}
 return <div className="ops-page" style={{padding:24}}><div className="ops-pageactions"><div><h1 style={{margin:0,fontSize:22}}>Automation Center</h1><p>Hesaplar, transfer onay kuyruğu, işlemler ve sistem logları</p></div><div style={{display:'flex',gap:8}}><Link className="ops-ghost" to="/"><ArrowLeft size={14}/> Panel</Link><button className="ops-ghost" onClick={()=>void load()}><RefreshCw size={14}/> Yenile</button><button className="ops-primary" disabled={busy==='dispatch'} onClick={()=>void dispatch()}><Play size={14}/> {busy==='dispatch'?'Başlatılıyor…':'Scraper’ı Şimdi Çalıştır'}</button></div></div>
 {loading?<div className="ops-state">Veriler yükleniyor…</div>:<><div className="ops-summary"><div><span>Accounts</span><strong>{accounts.length}</strong></div><div><span>Pending approvals</span><strong>{payments.filter(x=>x.status==='pending_approval').length}</strong></div><div><span>Transactions</span><strong>{txs.length}</strong></div><div><span>Audit events</span><strong>{logs.length}</strong></div></div>
 <section className="ops-panel"><div className="ops-panelhead"><div><h2>Transfer Onay Kuyruğu</h2><p>Onay yalnızca veritabanı durumunu değiştirir.</p></div></div><div className="ops-tablewrap"><table className="ops-table"><thead><tr><th>Tarih</th><th>Alıcı</th><th>IBAN</th><th>Tutar</th><th>Durum</th><th>İşlem</th></tr></thead><tbody>{payments.map(p=><tr key={p.id}><td>{new Date(p.created_at).toLocaleString('tr-TR')}</td><td>{p.destination_name||'—'}</td><td className="mono">{p.destination_iban_masked||'—'}</td><td>{money(Number(p.amount),p.currency)}</td><td><span className={`ops-badge ${p.status}`}>{p.status}</span></td><td>{p.status==='pending_approval'?<div style={{display:'flex',gap:6}}><button className="ops-small" disabled={busy===p.id} onClick={()=>void decide(p.id,'approved')}><Check size={13}/> Onayla</button><button className="ops-small" disabled={busy===p.id} onClick={()=>void decide(p.id,'rejected')}><X size={13}/> Reddet</button></div>:'—'}</td></tr>)}</tbody></table></div></section>
 <div className="ops-grid2"><section className="ops-panel"><div className="ops-panelhead"><div><h2>Banka Hesapları</h2><p>Son senkronize bakiye görünümü</p></div></div><div className="ops-tablewrap"><table className="ops-table"><thead><tr><th>Banka</th><th>Hesap</th><th>IBAN</th><th>Bakiye</th><th>Durum</th></tr></thead><tbody>{accounts.map(a=><tr key={a.id}><td>{a.bank_name}</td><td>{a.account_name}</td><td className="mono">{a.iban_masked}</td><td>{money(Number(a.balance),a.currency)}</td><td><span className={`ops-badge ${a.status}`}>{a.status}</span></td></tr>)}</tbody></table></div></section><section className="ops-panel"><div className="ops-panelhead"><div><h2>Audit Log</h2><p>Realtime operasyon olayları</p></div></div><div style={{padding:12}}>{logs.slice(0,12).map(l=><div key={l.id} style={{padding:'9px 0',borderBottom:'1px solid #edf1f5'}}><strong style={{fontSize:10}}>{l.action}</strong><div style={{fontSize:9,color:'#718096',marginTop:3}}>{l.detail||'—'} · {new Date(l.created_at).toLocaleString('tr-TR')}</div></div>)}</div></section></div></>}
 <div style={{position:'fixed',right:18,bottom:18,zIndex:100,display:'grid',gap:8}}>{toasts.map(t=><div key={t.id} style={{padding:'10px 13px',borderRadius:8,background:t.kind==='ok'?'#ecfdf5':'#fff1f2',border:`1px solid ${t.kind==='ok'?'#a7f3d0':'#fecdd3'}`,fontSize:11}}>{t.text}</div>)}</div></div>
}
