import { CircleAlert, Copy, DatabaseZap, RefreshCw } from 'lucide-react'
import { useOpsData, type BankAccount, type Tx } from '../../lib/opsData'

function cls(...v:(string|false|null|undefined)[]){return v.filter(Boolean).join(' ')}
function money(v:number,c='TRY'){try{return new Intl.NumberFormat('tr-TR',{style:'currency',currency:c,maximumFractionDigits:2}).format(Number(v||0))}catch{return `${Number(v||0).toFixed(2)} ${c}`}}
function dt(v:string|null|undefined){return v?new Date(v).toLocaleString('tr-TR'):'—'}
function dateOnly(v:string){return new Date(v).toLocaleDateString('tr-TR')}
function Badge({value}:{value:string|boolean}){const text=typeof value==='boolean'?(value?'Enabled':'Disabled'):String(value||'unknown');return <span className={`ops-badge ${text.toLowerCase().replaceAll(' ','-')}`}>{text}</span>}
function PageState({loading,error,reload}:{loading:boolean;error:string|null;reload:()=>void}){if(loading)return <div className="ops-state"><div className="ops-spinner"/><span>Live operations data is loading…</span></div>;if(error)return <div className="ops-error"><CircleAlert size={18}/><div><strong>Live data could not be loaded</strong><span>{error}</span></div><button onClick={reload}><RefreshCw size={14}/> Retry</button></div>;return null}
function Empty({title,detail}:{title:string;detail:string}){return <div className="ops-empty"><DatabaseZap size={30}/><strong>{title}</strong><span>{detail}</span></div>}
function Stat({label,value,note,tone='default'}:{label:string;value:string;note:string;tone?:'default'|'good'|'bad'|'warn'}){return <div className={`ops-stat ${tone}`}><span>{label}</span><strong>{value}</strong><small>{note}</small></div>}
function copyText(value:string){void navigator.clipboard?.writeText(value)}
function SummaryStrip(){const d=useOpsData();const deposits=d.transactions.filter(t=>Number(t.amount)>0).reduce((s,t)=>s+Math.abs(Number(t.amount)),0);const withdrawals=d.transactions.filter(t=>Number(t.amount)<0).reduce((s,t)=>s+Math.abs(Number(t.amount)),0);const total=d.accounts.reduce((s,a)=>s+Number(a.balance||0),0);return <div className="ops-summary"><div><span>Total balance</span><strong>{money(total,d.accounts[0]?.currency||'TRY')}</strong></div><div><span>Deposits</span><strong className="positive">+{money(deposits,d.accounts[0]?.currency||'TRY')}</strong></div><div><span>Withdrawals</span><strong className="negative">-{money(withdrawals,d.accounts[0]?.currency||'TRY')}</strong></div><div><span>Accounts</span><strong>{d.accounts.length}</strong></div></div>}
function TransactionTable({rows,accounts}:{rows:Tx[];accounts:BankAccount[]}){const account=(id:string|null)=>accounts.find(a=>a.id===id);return <div className="ops-tablewrap"><table className="ops-table"><thead><tr><th>Date</th><th>Completed at</th><th>Type</th><th>Transfer type</th><th>Counterparty</th><th>Counterparty IBAN</th><th>Account</th><th>Bank</th><th className="right">Amount</th><th className="right">Balance after</th><th>Status</th></tr></thead><tbody>{rows.map(t=>{const a=account(t.account_id);return <tr key={t.id}><td>{dateOnly(t.occurred_at)}<small>{new Date(t.occurred_at).toLocaleTimeString('tr-TR')}</small></td><td>{dt(t.occurred_at)}</td><td><Badge value={Number(t.amount)>=0?'Deposit':'Withdrawal'}/></td><td>{t.method||'—'}</td><td>{t.counterparty||'—'}</td><td><span className="ops-copy mono">{t.counterparty_iban_masked||'—'}{t.counterparty_iban_masked&&<button onClick={()=>copyText(t.counterparty_iban_masked||'')}><Copy size={12}/></button>}</span></td><td><strong>{a?.account_name||'—'}</strong></td><td>{a?.bank_name||'—'}</td><td className={cls('right amount',Number(t.amount)>=0?'positive':'negative')}>{Number(t.amount)>=0?'+':''}{money(Number(t.amount),a?.currency||'TRY')}</td><td className="right">{t.balance_after==null?'—':money(Number(t.balance_after),a?.currency||'TRY')}</td><td><Badge value={t.status}/></td></tr>})}</tbody></table></div>}

export { cls, money, dt, dateOnly, Badge, PageState, Empty, Stat, copyText, SummaryStrip, TransactionTable }
